services:
  thyrock-kalender:
    container_name: thyrock-kalender
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NITRO_PRESET: node_server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NITRO_PRESET: node_server
    ports:
      - "127.0.0.1:3000:3000"
