/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadIcsRouteImport } from './routes/download-ics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIcsRoute = DownloadIcsRouteImport.update({
  id: '/download-ics',
  path: '/download-ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/download-ics': typeof DownloadIcsRoute
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/download-ics': typeof DownloadIcsRoute
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/download-ics': typeof DownloadIcsRoute
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download-ics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download-ics'
  id: '__root__' | '/' | '/download-ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DownloadIcsRoute: typeof DownloadIcsRoute
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download-ics': {
      id: '/download-ics'
      path: '/download-ics'
      fullPath: '/download-ics'
      preLoaderRoute: typeof DownloadIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DownloadIcsRoute: DownloadIcsRoute,
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
